"""change

Revision ID: aac994d13911
Revises: 
Create Date: 2023-07-03 12:25:54.179909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac994d13911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('weekday_bandwidth', sa.Integer(), nullable=True),
    sa.Column('weekend_bandwidth', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_description'), 'services', ['description'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_index(op.f('ix_services_weekday_bandwidth'), 'services', ['weekday_bandwidth'], unique=False)
    op.create_index(op.f('ix_services_weekend_bandwidth'), 'services', ['weekend_bandwidth'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_weekend_bandwidth'), table_name='services')
    op.drop_index(op.f('ix_services_weekday_bandwidth'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_description'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
